/* Post-build: drop PNGs from dist/ that nothing references any more.
   Every image path in the source now points at a .webp twin, so shipping the
   PNG originals would roughly 10x the deploy for bytes no browser requests.

   Only dist/ is touched - a build artifact, regenerated by `npm run build`.
   The originals in public/ are never modified.

   A PNG is KEPT when it has no .webp twin (nothing converted it, so a
   reference may still exist) or when it is on ALWAYS_KEEP: the favicon and
   the Open Graph / Twitter card image, which are fetched by crawlers that do
   not reliably negotiate WebP.

   To ship the PNGs again, drop `&& node prune_dist_png.cjs` from the build
   script in package.json. */
const fs = require("fs");
const path = require("path");

const DIST = path.join(__dirname, "dist");
const ALWAYS_KEEP = new Set([
  "favicon-192x192.png",
  "blackscale CIRE logo.png",
  "blackscale_logo_white.png",
]);

if (!fs.existsSync(DIST)) {
  console.error("prune: no dist/ - run `vite build` first");
  process.exit(0);
}

let removed = 0, freed = 0, kept = 0;
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { walk(p); continue; }
    if (!/\.png$/i.test(e.name)) continue;
    const hasTwin = fs.existsSync(p.replace(/\.png$/i, ".webp"));
    if (!hasTwin || ALWAYS_KEEP.has(e.name)) { kept++; continue; }
    freed += fs.statSync(p).size;
    fs.unlinkSync(p);
    removed++;
  }
})(DIST);

console.log(
  `prune: removed ${removed} superseded PNGs (${(freed / 1048576).toFixed(0)} MB), kept ${kept}`,
);
